### ISSUE TITLE
Uncaught SyntaxError:

### ISSUE THREAD

**Issue by rasul-chopurov** [davidvandertuijn/laravel-google-maps#1]
Laravel 10x
PHP 8.3
Uncaught SyntaxError: Unexpected token ':' (at discover:82:24)

<img width="646" alt="Screenshot 2024-11-23 at 17 02 44" src="https://github.com/user-attachments/assets/02b2eacb-caea-4543-b52d-eb89ea3eed9b">

livewire component 

    public function render()
    {
        Mapper::map(40.388708, 49.834073, [
            'eventBeforeLoad' => 'console.log("before load");'
        ]);

        return view('livewire.discover');
    }
    
    view
    
    <div class="flex h-screen">

    
    <div class="w-1/3 bg-gray-100 overflow-y-scroll p-4">
        @foreach($branches as $branch)
            <div class="p-4 border-b cursor-pointer" wire:click="focusBranch({{ $branch['latitude'] }}, {{ $branch['longitude'] }})">
                <img src="{{ $branch['image'] }}" alt="{{ $branch['name'] }}" class="w-full h-32 object-cover rounded">
                <h2 class="text-lg font-bold mt-2">{{ $branch['name'] }}</h2>
                <p class="text-sm text-gray-600">{{ $branch['address'] }}</p>
            </div>
        @endforeach
    </div>

    
    <div class="w-2/3">
{{--        <div id="map" class="h-full w-full"></div>--}}
        <div class="h-full w-full">
            {!! Mapper::render() !!}
        </div>
    </div>
</div>

**Comment by davidvandertuijn** [comment]
This library is not build for Laravel Livewire.

**Comment by RomanDeNu** [comment]
I've worked around it by taking the if statements out and placing them around the key instead having an @else with the key again with the other value. @bahramzade
